"""" Vim Appearance

set lines=57 columns=120     " initial window size


"""" Miscellaneous settings that might be worth enabling

if has("gui_macvim")         " configure font
    set guifont=Iosevka\ SS07:h13
else
    set guifont=M+1Code\ Nerd\ Font\ Mono\ 13
endif
