"""" Vim Appearance

set lines=46 columns=120     " initial window size


"""" Miscellaneous settings that might be worth enabling

set background=light         " configure Vim to use brighter colors
