"""" Vim Appearance

set lines=46 columns=120     " initial window size


"""" Miscellaneous settings that might be worth enabling

if has("gui_macvim")         " configure font
    set guifont=Iosevka-SS07:h12
else
    set guifont=Iosevka\ SS07\ 12
endif
