import = [
  "~/.config/alacritty/themes/solarized_dark.toml",
  "~/.config/alacritty/fonts/M+1CodeNFM.toml",
]

[env]
TERM = "xterm-256color"

[shell]
program = "zsh"
args = ["--login"]

[font]
size = 13

[window]
blur = true
decorations = "buttonless"
opacity = 0.9
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 16
y = 14
