[font]
size = 14

[general]
import = [
  "~/.config/alacritty/themes/solarized_dark_patched.toml",
  "~/.config/alacritty/fonts/M+1CodeNFM.toml",
]

[window]
blur = true
decorations = "buttonless"
opacity = 0.9
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 57

[window.padding]
x = 16
y = 14

[terminal.shell]
program = "zsh"
args = ["--login"]
