[settings]
experimental = true
idiomatic_version_file_enable_tools = []
minimum_release_age = "2d"
prereleases = false
# python
python.uv_venv_auto = "create|source" # create .venv if missing, then activate

[tools]
bun = "latest"
lua = "5"
node = "lts"
"npm:@mariozechner/pi-coding-agent" = "latest"
python = "3.14"
ruby = "latest"
turbo = "2"
usage = "latest"
uv = "latest"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
